"""add price_alerts table

Revision ID: 76140c7b4c70
Revises: 7084456281bb
Create Date: 2026-05-22 08:52:43.747255+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "76140c7b4c70"
down_revision: Union[str, None] = "7084456281bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_alerts",
        sa.Column("good_id", sa.UUID(), nullable=False),
        sa.Column("market_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("previous_avg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delta_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("threshold_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["good_id"],
            ["goods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_alerts_good_market",
        "price_alerts",
        ["good_id", "market_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_alerts_good_market", table_name="price_alerts")
    op.drop_table("price_alerts")
    # ### end Alembic commands ###
